# Generated by Django 4.0.5 on 2022-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_events_remove_user_user_cart_user_senior_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.CharField(default=101, max_length=255),
        ),
    ]
