# Generated by Django 4.0.5 on 2022-06-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hidden_on_leaderboard',
        ),
    ]
