# Generated by Django 4.0.5 on 2022-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_current_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_cart',
            field=models.CharField(choices=[('1', 'NCC'), ('2', 'RC'), ('3', 'Datawiz')], default=0, max_length=3),
            preserve_default=False,
        ),
    ]
